default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: root
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: backend_nlw3_development

test:
  <<: *default
  database: backend_nlw3_test

production:
  <<: *default
  database: backend_nlw3_production
  username: backend_nlw3
  password: <%= ENV['BACKEND_NLW3_DATABASE_PASSWORD'] %>
